---
notifications:
  email: false
sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.4" CHECK=test
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.2.3
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.2.3
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=rubocop
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "ExSbFQsxOlpFTc/4TTGJElIx0/sYNZ1I2Nbd9EfGPNeECXBgmqTdJmPqdV6cl3mKDFh+tSSxnIDZe5BILhmxIR7aF2lbf8jwcbo2nxe9qAZ42GDKNV2klNXUjR7kA7tz220RNO9rM3HDKAwrKtCPtwQ0Q5u90YGGJDj2nr7NUaM="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
